disabled_rules:
  - opening_brace
  - large_tuple

included:

excluded:
  - Build
  - DerivedData
  - "**/resource_bundle_accessor.swift"

cyclomatic_complexity:
  ignores_case_statements: true

function_body_length: 100

identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - ok
    - ix

