name: smbc

settings:
  base:
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    CODE_SIGN_STYLE: Automatic
    DEAD_CODE_STRIPPING: YES
    DEVELOPMENT_TEAM: A3UXBEBE8Z
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    LOCALIZATION_PREFERS_STRING_CATALOGS: YES
    PRODUCT_NAME: $(TARGET_NAME)
    SWIFT_VERSION: 6.1
    SWIFT_EMIT_LOC_STRINGS: YES
    SWIFT_STRICT_CONCURRENCY: YES
  configs:
    debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG $(inherited)
    release:
      VALIDATE_PRODUCT:  YES

targets:
  smbc:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    dependencies:
      - package: MarkdownUI
    sources:
      - smbc
    entitlements:
      path: smbc/smbc.entitlements
      properties:
        com.apple.security.application-groups:
          - group.org.snafu.smbc
    settings:
      base:
        CURRENT_PROJECT_VERSION: 1
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: $(TARGET_NAME)
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.travel
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        INFOPLIST_KEY_UIBackgroundModes:
          - remote-notification
        MARKETING_VERSION: 1.0
        PRODUCT_BUNDLE_IDENTIFIER: org.snafu.smbc
    postBuildScripts:
      - path: .buildversion.sh
        name: Build Version
        showEnvVars: NO
        basedOnDependencyAnalysis: NO
      - path: .swiftlint.sh
        name: Swift Lint
        showEnvVars: NO
        basedOnDependencyAnalysis: NO

  smbcWidget:
    type: app-extension
    subtype: widgetkit-extension
    platform: iOS
    deploymentTarget: 17.0
  #   dependencies:
  #     - target: smbc
    sources:
      - smbcWidget
    entitlements:
      path: smbcWidget/smbcWidget.entitlements
      properties:
        com.apple.security.app-sandbox: YES
        com.apple.security.application-groups:
          - group.org.snafu.smbc
    settings:
      base:
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_FILE: smbcWidget/Info.plist
        INFOPLIST_KEY_CFBundleDisplayName: smbcWidget
        INFOPLIST_KEY_NSHumanReadableCopyright: Copyright 2025 Marco S Hyman
        INFOPLIST_KEY_NSEXTESION:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
        LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/Frameworks @executable_path/../../Frameworks
        MARKETING_VERSION: 1.0
        PRODUCT_NAME: $(TARGET_NAME)
        PRODUCT_BUNDLE_IDENTIFIER: org.snafu.smbcWidget
        REGISTER_APP_GROUPS: YES
        SKIP_INSTALL: YES
        TARGETED_DEVICE_FAMILY: 1,2

packages:
  MarkdownUI:
    url: git@github.com/gonzalezreal/swift-markdown-ui.git
    from: 2.3.0

