name: smbc

settings:
  base:
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    CODE_SIGN_STYLE: Automatic
    DEAD_CODE_STRIPPING: YES
    DEVELOPMENT_TEAM: A3UXBEBE8Z
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    LOCALIZATION_PREFERS_STRING_CATALOGS: YES
    MARKETING_VERSION: 1.0
    PRODUCT_NAME: smbc
    SWIFT_VERSION: 6.1
    SWIFT_EMIT_LOC_STRINGS: YES
    SWIFT_STRICT_CONCURRENCY: YES
  configs:
    debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG $(inherited)
    release:
      VALIDATE_PRODUCT:  YES

targets:
  smbc:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    dependencies:
      - package: MarkdownUI
      - target: smbcWidgetExtension
    sources:
      - smbc
    entitlements:
      path: smbc/smbc.entitlements
      properties:
        com.apple.security.application-groups:
          - group.org.snafu.smbc
    settings:
      base:
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: smbc
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.travel
        INFOPLIST_KEY_NSHumanReadableCopyright: Copyright 2025 Marco S Hyman
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        INFOPLIST_KEY_UIBackgroundModes:
          - remote-notification
        PRODUCT_BUNDLE_IDENTIFIER: org.snafu.smbc
    postBuildScripts:
      - path: .buildversion.sh
        name: Build Version
        showEnvVars: NO
        basedOnDependencyAnalysis: NO
      - path: .swiftlint.sh
        name: Swift Lint
        showEnvVars: NO
        basedOnDependencyAnalysis: NO

  smbcWidgetExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - smbcWidget
    dependencies:
      - sdk: SwiftUI.framework
      - sdk: WidgetKit.framework
    entitlements:
      path: smbcWidget/smbcWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.org.snafu.smbc
    # INFOPLIST_KEY_NSExtension doesn't seem to exist.
    # Build the Info.plist here so I can add that key/value
    # Entries automatically added by xcodegen are skipped
    info:
      path: smbcWidget/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleDisplayName: smbcWidgetExtension
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
        NSHumanReadableCopyright: Copyright 2025 Marco S Hyman
    settings:
      base:
        GENERATE_INFOPLIST_FILE: NO
        SKIP_INSTALL: YES
        PRODUCT_NAME: smbcWidgetExtension
        PRODUCT_BUNDLE_IDENTIFIER: org.snafu.smbc.smbcWidgetExtension
    postBuildScripts:
      # - path: .buildversion.sh
      #   name: Build Version
      #   showEnvVars: NO
      #   basedOnDependencyAnalysis: NO
      - path: .swiftlint.sh
        name: Swift Lint
        showEnvVars: NO
        basedOnDependencyAnalysis: NO

packages:
  MarkdownUI:
    url: git@github.com/gonzalezreal/swift-markdown-ui.git
    from: 2.3.0

